# Generated by Django 4.1.2 on 2022-10-05 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, verbose_name='Email')),
                ('rol', models.CharField(max_length=20, verbose_name='Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('idconductor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('email', models.CharField(max_length=80, verbose_name='Email')),
                ('direccion', models.CharField(max_length=80, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('idruta', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombreruta', models.CharField(max_length=50, verbose_name='Nombre')),
                ('valor', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('idplaca', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('tarjeta', models.DateField(verbose_name='Tarjeta')),
                ('soat', models.DateField(verbose_name='Soat')),
                ('tecnomecanica', models.DateField(verbose_name='Tecnomecanica')),
                ('extintor', models.DateField(verbose_name='Extintor')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo', to=settings.AUTH_USER_MODEL)),
                ('idconductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo', to='authApp.conductor')),
            ],
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('iddespacho', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despacho', to=settings.AUTH_USER_MODEL)),
                ('idplaca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despacho', to='authApp.vehiculo')),
                ('idruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despacho', to='authApp.ruta')),
            ],
        ),
    ]
